name: Add Ticket Number to PR Title

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write

jobs:
  update-title:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Title
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.REPO_ACCESS_TOCKEN }}
          script: |
            const prTitle = '${{ github.event.pull_request.title }}';
            const prNumber = ${{ github.event.pull_request.number }};
            console.log(`Current PR Title: ${prTitle}`);
            console.log(`PR Number: ${prNumber}`);

            // Regex to check if the title already has a ticket number (e.g. Ticket_123)
            const ticketPattern = /Ticket_\d+/i;

            if (!ticketPattern.test(prTitle)) {
              const newTitle = `Ticket_${prNumber} ${prTitle}`;
              console.log(`Updating PR Title to: ${newTitle}`);

              // Utilisation correcte de l'API GitHub
              await github.pulls.update({
                owner: '${{ github.repository_owner }}',
                repo: '${{ github.event.repository.name }}',
                pull_number: prNumber,
                title: newTitle
              });
              console.log(`PR title updated to: ${newTitle}`);
            } else {
              console.log('The title already contains a ticket number.');
            }
